#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Crocodile.Resource", IsApplication=true)]

namespace Crocodile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Croco = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Instruction = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int NewGame = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int NextWord = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int InstructionButton = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int NewGameButton = 2131165198;
			
			// aapt resource value: 0x7f070002
			public const int NextWordButton = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int checkBox1 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int checkBox2 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int checkBox3 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int checkBox4 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int checkBox5 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int checkBox6 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int checkBox7 = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int imageViewCroco = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int imageWord = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayoutButtons = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int linearLayoutCategories = 2131165188;
			
			// aapt resource value: 0x7f07000f
			public const int menuHelp = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int menuSettings = 2131165200;
			
			// aapt resource value: 0x7f070001
			public const int textView1 = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int action_menu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int preferences = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040009
			public const int Adult = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int Character = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int Conception = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int Instruction = 2130968586;
			
			// aapt resource value: 0x7f040004
			public const int Nature = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int NewGame = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Next = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int Other = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int People = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int Profession = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
